version: '3'
services:
  db:
    image: postgres:latest
    container_name: wegfinder-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wegfinder
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"